---
title: Comparing the bacterial growth on mobile cell phones of regular college students
  versus of college students working in hospitals
author: "Angela Jocson"
date: "8/27/2019"
output:
  html_document:
    df_print: paged
csl: bioinformatics.csl
bibliography: references.bib
---

# Overview of Proposed Project 

Cell phones have become an essential part of modern-day lifestyle, in fact, most people tend to not leave the house unless they have their cell phone present. With cell phones becoming more a necessity rather than an accessory, it is interesting to see how much our cell phones can collect from our daily lives. It is also more worrisome rather than interesting to realize how much bacteria our cell phones can bring in, especially when working in expectedly sterile environments such as hospitals or emergency rooms. Karabay et. al (2007) found that health professionals in a teaching hospital in Turkey carried around cell phones that did get contiminated with bacteria such as E. coli which then can cause hospital infections. Another study in 2009, found that 94.5% of their phones sampled from Healthcare Workers showed evidence of bacterial contamination [@ulger2009we]. My project attempts to look more into whether there is a need for more regulation on the hygeine of our cell phones (especially if we work in a hospital setting) [@sepehri2009bacterial]. 

In this project I plan to test different samples of cell phone screens from regular college students who do not work in the health professions versus college students who are cleared to work in a hospital setting. I was interested in students specifically due to their high-use of phones and from a study finding that there is a higher level of bacterial contimination found in secondary students' mobile phone [@koljalg2017high]. I will be sampling random students in the University of San Francisco, but limiting it to students who carry their phones everywhere (even when working in clinical sites). 

# Question
Do students who work in hospitals/ health professions have fewer bacterial species growing on their cell phones than students who work outside of the medical field? 

# Hypothesis
Students who enter hospitals with their phones tend to sanitize before and after entering hosptal rooms, thus having less bacteria than those who can use their phones freely.

# Study Design
I will be sampling students at the University of San Francisco who either work in a hospital setting (where they are supposed to clean off their phones) versus students who carry their phones regularly on a daily basis. I will collect phone samples from six different students who fit into one of the two categories of the students. This will leave me with three samples from those who should be sanitizing their phones before after entering a hospital and from the regular student group.

### Suplies Needed for Sampling

1. Gloves
2. Sterile Swabbing kit
3. Sterile tubes + buffer 

### Sampling Plan

In order to confirm the necessary cell phone sanitizing routine when working in hospitals/ medical professional settings, I will attempt to sample this group of students after they come back from working at their clinical sites. This will be at Saint Mary's Clinical site at 1:30 pm, Tuesday September 3, immediately after the students get out of lab. To avoid students cleaning their phones solely because of their knowledge of being tested, I will gain permission to swab their phones on site. After swabbing the health professionals, I also plan on swabbing the phones of students who use their phones freely around the same time to avoid bacterial differences due to people using their phones for longer further in the day. This will be on Tuesday September 3 as well but during the 2:10-4:45 pm allotted laboratory time. 

# Works Cited

